version: '3'

services:
  ghost:
    image: ghost:4.32.0
    container_name: ghost
    volumes:
      - $PWD/..:/var/lib/ghost/content/themes/weiss-pro
      - ./ghost.db:/var/lib/ghost/content/data/ghost.db
    environment:
      - NODE_ENV=development
      - WEBHOOK_SECRET=
    ports:
      - 2368:2368
